version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: Booking-Laravel-React
    volumes:
      - ./backend:/var/www:cached  # Tối ưu tốc độ đọc ghi trên Windows/macOS
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: db_web_gshop
      DB_USERNAME: root
      DB_PASSWORD: secret
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend
    container_name: react_app
    ports:
      - "3000:80"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db_web_gshop
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gshop
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8080:80"

volumes:
  mysql_data:
